spring:
  boot:
    admin:
      client:
        url: http://192.168.139.61:8084
  zipkin:
    base-url: http://192.168.139.61:9411
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
    registerWithEureka: true   #服务端模式   集群模式为true
    fetchRegistry: true        #服务端模式    集群模式为true
    serviceUrl:
      defaultZone: http://192.168.139.61:8761/eureka/,http://192.168.139.61:8861/eureka/,http://192.168.139.61:8961/eureka/



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info